### ISSUE TITLE
Pale Moon browser

### ISSUE THREAD

**Issue by bdqp** [gtranslate/gtranslate#53]
Hi - I wonder if you could try to make gtranslate addon compatible with a Firefox fork called Pale Moon? It's a pre-Australis version of Firefox that is compatible with most other addons, but unfortunately not with gtranslate.

I read on their forum that the reason for incompatibility is something to do with chrome manifest GUID hardcoded to Firefox? That doesn't make a lot of sense to me, but they suggest it is simple to fix.

http://forum.palemoon.org/viewtopic.php?f=3&t=6473

Thanks - really appreciate the excellent addon!

**Comment by bpierre** [comment]
@mb1234 Could you give me the Pale Moon browser’s GUID? I cannot post on the thread, but I don’t see any problem to support Pale Moon: don’t hesitate to open a pull request with the change.

**Comment by mb1234** [comment]
According to instructions on the site, there should be a file called "chrome.manifest" included with the addon. The following line need to be appended to chrome.manifest. The GUID is the hex string in curly brackets.

overlay chrome://browser/content/browser.xul chrome://optionsmenu/content/OptionsMenuOverlayFF.xul application={8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}

I looked inside your code and didn't see a chrome.manifest file so... I'm lost. Hopefully it makes some sense to you :)

**Comment by bpierre** [comment]
Closing this as Pale Moon doesn’t support Web Extensions.
